name: Scrape Talk Locations

on:
  workflow_dispatch:
  push:
    paths:
      - '_talks/**'
      - 'talkmap.ipynb'
      - 'talkmap.py'

concurrency:
  group: talk-map-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write           # This workflow pushes to the repository

    steps:
    - uses: actions/checkout@v7

    - name: Set up Python
      uses: actions/setup-python@v7
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        pip install jupyter pandas requests beautifulsoup4 geopy
        pip install getorg --upgrade

    - name: Run Jupyter Notebook
      run: |
        jupyter nbconvert --to notebook --execute talkmap.ipynb --output talkmap_out.ipynb

    - name: Commit changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add talkmap/org-locations.js talkmap_out.ipynb
        git commit -m "Automated update of talk locations" || echo "No changes to commit"
        git push origin "HEAD:${GITHUB_REF_NAME}"
